int main() {
	int dexter;
	int deedee;
	int zeke;
	dexter = 155;
	deedee = 2047;
	zeke = dexter == deedee;
	printf("%d\n", zeke);
	zeke = dexter != deedee;
	printf("%d\n", zeke);
	zeke = dexter <= deedee;
	printf("%d\n", zeke);
	zeke = dexter < deedee;
	printf("%d\n", zeke);
	zeke = dexter >= deedee;
	printf("%d\n", zeke);
	zeke = dexter > deedee;
	printf("%d\n", zeke);
	zeke = !zeke;
	printf("%d\n", zeke);
	dexter = 2047;
	deedee = 2047;
	zeke = dexter == deedee;
	printf("%d\n", zeke);
	zeke = dexter != deedee;
	printf("%d\n", zeke);
	zeke = dexter <= deedee;
	printf("%d\n", zeke);
	zeke = dexter < deedee;
	printf("%d\n", zeke);
	zeke = dexter >= deedee;
	printf("%d\n", zeke);
	zeke = dexter > deedee;
	printf("%d\n", zeke);
	zeke = !zeke;
	printf("%d\n", zeke);
	dexter = 2047;
	deedee = 155;
	zeke = dexter == deedee;
	printf("%d\n", zeke);
	zeke = dexter != deedee;
	printf("%d\n", zeke);
	zeke = dexter <= deedee;
	printf("%d\n", zeke);
	zeke = dexter < deedee;
	printf("%d\n", zeke);
	zeke = dexter >= deedee;
	printf("%d\n", zeke);
	zeke = dexter > deedee;
	printf("%d\n", zeke);
	zeke = !zeke;
	printf("%d\n", zeke);
}
